### PR TITLE
BadgerDB: Batch and Iterator Functionality

### PR DESCRIPTION
**Pull request by dutterbutter**
## Changes
- Added batchWrites functionality
- Updated database interfaces to include Batch interface methods
- Sets a batch of key-value pairs in mapping and then writes that batch to the database
- Added iterator functionality 
- Updated database interfaces to include Iterator interface methods
- Allows users to iterate over keys

## Tests:
```
go test ./polkadb
```

### Fixes: #

### CODE REVIEW

**Comment by dutterbutter** [comment]
@ansermino @noot updated PR to include iterator and tests

**Comment by dutterbutter** [comment]
> nice work! just curious, tests took 64 seconds to run on my computer is that normal?

That seems off...tests run in ~2.3 seconds on my computer with a clean `--testcache`

We will have to add some benchmarking for the db and have that being reported like we have test coverage

**Comment by noot** [comment]
@dutterbutter  how do I clean the cache?

**Comment by dutterbutter** [comment]
> @dutterbutter how do I clean the cache?

`go clean -testcache`

**Comment by noot** [comment]
@ansermino @priom thoughts?

**Comment by priom** [comment]
took 2.9 sec on my computer :D @dutterbutter

**Pull request merged**
