### PR TITLE
MemoryDB 

### PR DESCRIPTION
**Pull request by dutterbutter**
## Changes
- Added `memoryDB.go` 
- Wraps an initialized mapping to *MemDatabase type
- Unit tests in place 

## Tests:
```
go test ./polkadb/...
```

### Fixes:

### CODE REVIEW

**Comment by dutterbutter** [comment]
> im getting this error when running the tests
> 
> ```
> polkadb/memoryDB_test.go:8:19: undefined: data
> polkadb/memoryDB_test.go:9:13: undefined: data
> FAIL	github.com/ChainSafeSystems/gossamer/polkadb [build failed]
> ```

Should be resolved now.

**Comment by noot** [comment]
@dutterbutter nice thank you

**Comment by dutterbutter** [comment]
I can't merge this until Travis resolves, is there any reason why it would be stuck? @GregTheGreek

**Comment by ansermino** [comment]
@dutterbutter Because you don't have travis config in your branch. Please wait a few and we will get it resolved

**Pull request merged**
